# ============================================
# Park Injury Reporting System - Shiny App
# ============================================

library(shiny)
library(DBI)
library(RPostgres)
library(dplyr)

# ============================================
# 1. Load Environment Variables
# ============================================
readRenviron(".env")

# ============================================
# 2. Database Connection Function
# ============================================
get_con <- function() {
  dbConnect(
    RPostgres::Postgres(),
    dbname = Sys.getenv("SUPABASE_DB", "postgres"),
    host = Sys.getenv("SUPABASE_HOST"),
    port = as.integer(Sys.getenv("SUPABASE_PORT", "5432")),
    user = Sys.getenv("SUPABASE_USER", "postgres"),
    password = Sys.getenv("SUPABASE_PASSWORD")
  )
}

# ============================================
# 3. Initialize Database (Create Table + Seed Data)
# ============================================
init_database <- function() {
  con <- get_con()
  
  # Check if table exists
  tables <- dbListTables(con)
  
  if (!"park_injuries" %in% tables) {
    cat("📋 Table 'park_injuries' does not exist. Creating...\n")
    
    # Create Table
    dbExecute(con, "
      CREATE TABLE park_injuries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        report_date DATE NOT NULL,
        park_name TEXT NOT NULL,
        location_detail TEXT NOT NULL,
        injury_type TEXT NOT NULL,
        severity_level INTEGER CHECK (severity_level BETWEEN 1 AND 5),
        description TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      )
    ")
    
    # Insert Synthetic Data (Seed Data)
    synthetic_data <- data.frame(
      report_date = as.Date(c("2023-10-01", "2023-10-05", "2023-10-10")),
      park_name = c("Central Park", "Riverside Park", "Central Park"),
      location_detail = c("Playground", "Hiking Trail", "Basketball Court"),
      injury_type = c("Fall", "Sprain", "Collision"),
      severity_level = c(2, 3, 4),
      description = c("Child fell off swing", "Ankle twisted on rock", "Players collided"),
      stringsAsFactors = FALSE
    )
    
    dbAppendTable(con, "park_injuries", synthetic_data)
    cat("✅ Inserted", nrow(synthetic_data), "rows of synthetic data\n")
  } else {
    cat("✅ Table 'park_injuries' already exists\n")
  }
  
  # Verify and display record count
  count <- dbGetQuery(con, "SELECT COUNT(*) as n FROM park_injuries")$n
  cat("📊 Current total records:", count, "\n")
  
  dbDisconnect(con)
}

# 🚀 Initialize Database on Startup
init_database()

# ============================================
# 4. UI Interface
# ============================================
ui <- fluidPage(
  titlePanel("🏞️ Park Injury Reporting System"),
  
  sidebarLayout(
    # ===== Left Panel: Input Form =====
    sidebarPanel(
      h3("📝 Submit New Report"),
      
      # selectInput - Park Name
      selectInput(
        inputId = "park_name",
        label = "Park Name",
        choices = c("Central Park", "Riverside Park", "Sunset Park", "Liberty Park"),
        selected = "Central Park"
      ),
      
      # dateInput - Incident Date
      dateInput(
        inputId = "report_date",
        label = "Incident Date",
        value = Sys.Date()
      ),
      
      # textInput - Specific Location
      textInput(
        inputId = "location_detail",
        label = "Specific Location",
        placeholder = "e.g., Playground, North Trail"
      ),
      
      # selectInput - Injury Type
      selectInput(
        inputId = "injury_type",
        label = "Injury Type",
        choices = c("Fall", "Sprain", "Collision", "Cut", "Other"),
        selected = "Fall"
      ),
      
      # numericInput - Severity Level
      numericInput(
        inputId = "severity_level",
        label = "Severity Level (1-5)",
        value = 2,
        min = 1,
        max = 5,
        step = 1
      ),
      
      # textInput - Detailed Description
      textInput(
        inputId = "description",
        label = "Detailed Description",
        placeholder = "Briefly describe the incident..."
      ),
      
      # actionButton - Submit Button
      actionButton(
        inputId = "submit_btn",
        label = "✅ Submit Report",
        class = "btn-primary",
        width = "100%"
      ),
      
      # Submission Status Message
      verbatimTextOutput("submit_status")
    ),
    
    # ===== Right Panel: Data Display =====
    mainPanel(
      h3("📊 Statistics"),
      
      # Statistics Text
      textOutput("total_count"),
      br(),
      textOutput("avg_severity"),
      
      # Recent Records Table
      h4("📋 Recent 10 Records"),
      tableOutput("recent_records")
    )
  )
)

# ============================================
# 5. Server Logic
# ============================================
server <- function(input, output, session) {
  
  # ===== Event: Submit Form → Write to Database =====
  observeEvent(input$submit_btn, {
    # Validate Input
    if (input$location_detail == "") {
      showNotification("⚠️ Please fill in the specific location", type = "warning")
      return()
    }
    
    # Prepare New Record
    new_record <- data.frame(
      report_date = as.Date(input$report_date),
      park_name = input$park_name,
      location_detail = input$location_detail,
      injury_type = input$injury_type,
      severity_level = as.integer(input$severity_level),
      description = input$description,
      stringsAsFactors = FALSE
    )
    
    # Write to Database (Using dbAppendTable to append data)
    con <- NULL
    tryCatch({
      con <- get_con()
      dbAppendTable(con, "park_injuries", new_record)
      output$submit_status <- renderText({"✅ Submission Successful!"})
      showNotification("Report submitted successfully!", type = "message")
      
      # Clear partial form
      updateTextInput(session, "location_detail", value = "")
      updateTextInput(session, "description", value = "")
      updateNumericInput(session, "severity_level", value = 2)
      
    }, error = function(e) {
      output$submit_status <- renderText({paste("❌ Submission Failed:", e$message)})
      showNotification(paste("Submission Failed:", e$message), type = "error")
    }, finally = {
      if (!is.null(con)) dbDisconnect(con)
    })
  })
  
  # ===== Output: Total Count =====
  output$total_count <- renderText({
    con <- NULL
    tryCatch({
      con <- get_con()
      n <- dbGetQuery(con, "SELECT COUNT(*) as n FROM park_injuries")$n
      paste("📊 Total Reports:", n)
    }, finally = {
      if (!is.null(con)) dbDisconnect(con)
    })
  })
  
  # ===== Output: Average Severity =====
  output$avg_severity <- renderText({
    con <- NULL
    tryCatch({
      con <- get_con()
      avg <- dbGetQuery(con, "SELECT AVG(severity_level) as avg FROM park_injuries")$avg
      paste("⚠️ Average Severity:", round(avg, 2))
    }, finally = {
      if (!is.null(con)) dbDisconnect(con)
    })
  })
  
  # ===== Output: Recent Records Table =====
  output$recent_records <- renderTable({
    con <- NULL
    tryCatch({
      con <- get_con()
      data <- dbGetQuery(con, "
        SELECT report_date, park_name, location_detail, injury_type, severity_level, description 
        FROM park_injuries 
        ORDER BY report_date DESC 
        LIMIT 10
      ")
      
      # ✅ FIX DATE DISPLAY: Convert date to character format
      if(nrow(data) > 0) {
        data$report_date <- format(as.Date(data$report_date), "%Y-%m-%d")
      }
      
      return(data)
    }, finally = {
      if (!is.null(con)) dbDisconnect(con)
    })
  },
  na.strings = "",
  striped = TRUE,
  hover = TRUE,
  width = "100%",
  rownames = FALSE)
}

# ============================================
# 6. Run Application
# ============================================
shinyApp(ui = ui, server = server)
